S3 bucket snapshot server side encryption
bcgov/nr-apm-stack pull request #200
Opened 2022-06-30 18:15 UTC by GraceRuan

S3 bucket snapshot server side encryption

2022-06-30 23:24 UTC, mbystedt requested changes

2022-07-05 21:08 UTC, GraceRuan commented on workflow-cli/src/services/opensearch-snapshot.service.ts
> +        'x-amz-server-side-encryption': 'AES256',
I have changed to server-side-encryption in setting block. But it failed in lambda ci workflow

2022-07-05 21:49 UTC, mbystedt requested changes

2022-07-05 21:51 UTC, mbystedt commented on workflow-cli/src/services/opensearch-snapshot.service.ts
> +          'server-side-encryption': true,
Running this should fix it: npm run lint -- --fix

Everything after the -- is passed through to the command.

2022-07-07 20:19 UTC, andrwils commented
We're now using PR 202 for these changes.

2022-07-07 20:19 UTC, closed without merging